version: "3.4"
services:
    bookstore_db:
        image: postgres:13.2-alpine
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=bookstore
        ports:
        - 5432:5432